project:
  type: website
  output-dir: docs

website:
  title: "Introduction"
  description: >
    Course Projects for STA 9750 at Baruch College
  site-url: "https://chentenchig.github.io/STA9750-2025-FALL/"
  navbar:
    background: primary
    search: false

format:
  html: default

editor:
  mode: source
